In [1]:
%pip install -q ipytest pytest

Note: you may need to restart the kernel to use updated packages.


In [6]:
import ipytest
import pytest

ipytest.autoconfig()

In [7]:
%pip install -q numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [40]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix
    
    #СЛОЖЕНИЕ МАТРИЦ

    def __add__(self, other):
        if isinstance(other, Matrix):
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):
                result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
                for i in range(len(self.matrix)):
                    for n in range(len(self.matrix[0])):
                        result[i][n] = self.matrix[i][n] + other.matrix[i][n]
                return Matrix(result)
            else:
                raise ValueError('Matrices gotta be the same shape!')
        elif isinstance(other, (int, float)):
            result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] + other
            return Matrix(result)
        else: 
            raise TypeError("An argument is gotta be Matrix's object, int or float!")    
    #Вычитание

    def __sub__(self, other):
        if isinstance(other, Matrix):
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):
                result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
                for i in range(len(self.matrix)):
                    for n in range(len(self.matrix[0])):
                        result[i][n] = self.matrix[i][n] - other.matrix[i][n]
                return Matrix(result)
            else:
                raise ValueError("Matrices are gotta be the same shape!")
        elif isinstance(other, (int, float)):
            result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] - other
            return Matrix(result)
        else:
            raise TypeError("An argument is gotta be Matrix's object or int/float!")


    #Деление
    def __truediv__(self, other):
        if isinstance(other, Matrix):
            
            if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
                raise ValueError('Matrices gotta be the same shape!')

            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]

            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] / other.matrix[i][n]

            return Matrix(result)

        elif isinstance(other, (int, float)):
            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]

            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] / other

            return Matrix(result)

        else:
            raise ValueError("An argument is gotta be Matrix's object or int/float")

    # Умножение 
    def __mul__(self, other):
        if isinstance(other, Matrix):
            if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
                raise ValueError("Matrices are gotta be the same shape!")
            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] * other.matrix[i][n]
            return Matrix(result)
        elif isinstance(other, (int, float)):
            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] * other
            return Matrix(result)
        else:
            raise ValueError("An argument is gotta be Matrix's object or int/float")
    
    # Перемножение матриц 

    def __matmul__(self, other):
        if isinstance(other, (int, float)):
            result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for n in range(len(self.matrix[0])):
                    result[i][n] = self.matrix[i][n] * other
            return Matrix(result)   
        elif isinstance(other, Matrix):
            if len(self.matrix[0]) == len(other.matrix):
                result = [[0] * len(other.matrix[0]) for _ in range(len(self.matrix))]
                for i in range(len(self.matrix)):
                    for n in range(len(other.matrix[0])):
                        for k in range(len(other.matrix)):
                            result[i][n] += self.matrix[i][k] * other.matrix[k][n]
                return Matrix(result)
            else:
                raise ValueError("The number of columns in the first matrix does not match the number of rows in the second matrix!")
        else:
            raise TypeError("An argument is gotta be Matrix's object or int/float!")
        
    # Транспонирование матрицы
    
    def T(self):
        rows = len(self.matrix)
        cols = len(self.matrix[0])
    # Создание новой матрицы с транспонированными размерами
        result = [[0 for _ in range(rows)] for _ in range(cols)]

    # Заполнение элементов новой матрицы значениями из исходной матрицы
        for i in range(rows):
            for n in range(cols):
                result[n][i] = self.matrix[i][n]

        return Matrix(result)

    # Равенство 
    def __eq__(self, other):
        result = []
        for i in range(len(self.matrix)):
            row = []
            for n in range(len(self.matrix[0])):
                row.append((self.matrix[i][n]) == (other.matrix[i][n]))
            result.append(row)
        return Matrix(result)
    
    # Представление 
    def __repr__(self):
        return repr(self.matrix)


In [47]:
# Пример использования класса
matrix1 = [[1, 2, 3], [3, 4, 6], [55, 2, 10]]
matrix2 = [[5, 6, 3], [7, 8, 9], [22, 12, 21]]

my_matrix1 = Matrix(matrix1)
my_matrix2 = Matrix(matrix2)

result1 = my_matrix1 + my_matrix2
result2 = my_matrix1 - my_matrix2
result3 = my_matrix1 * my_matrix2
result4 = my_matrix1 / 2
result5 = my_matrix1 @ my_matrix2
result6 = my_matrix1.T()

# Вывод результатов
print(result1.matrix)
print(result2.matrix)
print(result3.matrix)
print(result4.matrix)
print(result5.matrix)
print(result6.matrix)





[[6, 8, 6], [10, 12, 15], [77, 14, 31]]
[[-4, -4, 0], [-4, -4, -3], [33, -10, -11]]
[[5, 12, 9], [21, 32, 54], [1210, 24, 210]]
[[0.5, 1.0, 1.5], [1.5, 2.0, 3.0], [27.5, 1.0, 5.0]]
[[85, 58, 84], [175, 122, 171], [509, 466, 393]]
[[1, 3, 55], [2, 4, 2], [3, 6, 10]]


In [56]:
matrix3 = [[2,7,8],[22,3,4],[5,1,6]]
matrix4 = [[1,2,3],[4,5,6],[7,8,9]]

np_matrix1 = np.array(matrix3)
np_matrix2 = np.array(matrix4)

print(np_matrix1 + np_matrix2)
print('____________')
print(np_matrix1 - np_matrix2)
print('____________')
print(np_matrix1 * np_matrix2)
print('____________')
print(np_matrix1 / 2)
print('____________')
print(np_matrix1 @ np_matrix2)
print('____________')
print(np_matrix1.T)


[[ 3  9 11]
 [26  8 10]
 [12  9 15]]
____________
[[ 1  5  5]
 [18 -2 -2]
 [-2 -7 -3]]
____________
[[ 2 14 24]
 [88 15 24]
 [35  8 54]]
____________
[[ 1.   3.5  4. ]
 [11.   1.5  2. ]
 [ 2.5  0.5  3. ]]
____________
[[ 86 103 120]
 [ 62  91 120]
 [ 51  63  75]]
____________
[[ 2 22  5]
 [ 7  3  1]
 [ 8  4  6]]


In [42]:
%%ipytest

matrix1 = Matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = Matrix([[1,2,3],[4,5,6],[7,8,9]])


@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 + matrix2).matrix) == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 + number).matrix) == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 - matrix2).matrix) == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 - number).matrix) == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (np.array(matrix1.T().matrix) == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 * matrix2).matrix) == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 * number).matrix) == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 / matrix2).matrix) == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 / number).matrix) == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (np.array((matrix1 @ matrix2).matrix) == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'

..........                                                                                   [100%]
10 passed in 0.04s
